# Generated by Django 3.2.8 on 2021-10-29 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='avatar_pict')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='youremail@company.com', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('bio', models.TextField(default='', max_length=250, null=True)),
                ('status', models.CharField(choices=[('Infected', 'Infected'), ('Not Infected', 'Not Infected')], default='Not Infected', max_length=20)),
                ('vaccinated_status', models.CharField(choices=[('Fully Vaccinated', 'Fully Vaccinated'), ('Not Vaccinated', 'Not Vaccinated'), ('First Dose', 'First Dose')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
